# Generated by Django 2.1 on 2019-03-10 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('teacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usnclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.IntegerField(default=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Myclass')),
            ],
        ),
        migrations.AddField(
            model_name='myclass',
            name='ban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Usnclass'),
        ),
    ]
